### ISSUE TITLE
Unknown Skeleton after defining joints in preprocess.py

### ISSUE THREAD

**Issue by DerpyMan101** [DeepMotionEditing/deep-motion-editing#128]
I still get error 

`Traceback (most recent call last):
  File "datasets/preprocess.py", line 67, in <module>
    collect_bvh(prefix, character, files)
  File "datasets/preprocess.py", line 19, in collect_bvh
    file = BVH_file(data_path + character + '/' + motion)
  File "/home/graham/Desktop/deep-motion-editing-master/retargeting/datasets/bvh_parser.py", line 126, in __init__
    raise Exception('Unknown skeleton')
Exception: Unknown skeleton
graham@graham-Virtualbox:~/Des`

even after defining the joints and effectors in preprocess.py.

**Comment by DerpyMan101** [comment]
I have fixed this error after removing a part of the skeleton and adding the if statements, but now I get the error:

``Traceback (most recent call last):
  File "datasets/preprocess.py", line 67, in <module>
    collect_bvh(prefix, character, files)
  File "datasets/preprocess.py", line 19, in collect_bvh
    file = BVH_file(data_path + character + '/' + motion)
  File "/home/graham/Desktop/deep-motion-editing-master/retargeting/datasets/bvh_parser.py", line 280, in __init__
    raise Exception('Problem in file', file_path)
Exception: ('Problem in file', './datasets/Mixamo/Spongebob/BossIntro_Shot_001.bvh')

**Comment by DerpyMan101** [comment]
Ok, I believe is resulting because the data is from outside of mixamo, so I used a different model and used animations from mixamo and the preprocessing worked, but when running train.py it results in this error:

`  File "train.py", line 54, in <module>
    main()
  File "train.py", line 38, in main
    model.optimize_parameters()
  File "/home/graham/Desktop/deep-motion-editing-master/retargeting/models/architecture.py", line 249, in optimize_parameters
    self.backward_D()
  File "/home/graham/Desktop/deep-motion-editing-master/retargeting/models/architecture.py", line 174, in backward_D
    fake = self.fake_pools[i].query(self.fake_pos[2 - i])
IndexError: list index out of range
`
