### ISSUE TITLE
Running "sh demo.sh" on Colab

### ISSUE THREAD

**Issue by guillermoAlv** [DeepMotionEditing/deep-motion-editing#168]
Hi, I'm trying to run the demo.sh script on colab (GPU environment) but i get the following error: 
loading from ./pretrained/models/topology0
loading from epoch 20000......
load succeed!
loading from ./pretrained/models/topology1
loading from epoch 20000......
load succeed!
Fixing foot contact using IK...
  0% 0/50 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "demo.py", line 46, in <module>
    example('Aj', 'BigVegas', 'Dancing Running Man.bvh', 'intra', './examples/intra_structure')
  File "demo.py", line 42, in example
    height)
  File "/content/deep-motion-editing/retargeting/models/IK.py", line 139, in fix_foot_contact
    ik_solver.step()
  File "/content/deep-motion-editing/retargeting/models/Kinematics.py", line 172, in step
    loss.backward()
  File "/usr/local/lib/python3.7/dist-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/__init__.py", line 149, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [324, 3, 3]], which is output 0 of ViewBackward, is at version 37; expected version 35 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
[2]

Any clue about what could it be the problem?
Thanks a lot for your time

**Comment by PeizhuoLi** [comment]
Hi, I've received similar issue recently in #166 (though in Chinese). I wasn't able to reproduce this error in my environment. You may try to follow this `Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).` You could also provide more details on your environment (such as python, pytorch version) so I can fix it on my machine.

**Comment by cdasomers** [comment]
I'm running into this problem even with the fixed code.  I solved it by downgrading pytorch to 1.4.

**Comment by johnmarkgibbons** [comment]
I also had this error with torch=1.9 and it was resolved when I downgraded to torch=1.4

**Comment by PeizhuoLi** [comment]
Thank you for your report. I have just fixed this issue. Please let me know if it still exists.
