### ISSUE TITLE
motion retargeting train problem

### ISSUE THREAD

**Issue by Lily-Shawn** [DeepMotionEditing/deep-motion-editing#174]
sorry to interupt.when I train it ,after run"python train.py --save_dir=./training/". it show these:
load from file ./datasets/Mixamo/Aj.npy
Traceback (most recent call last):
  File "train.py", line 54, in <module>
    main()
  File "train.py", line 23, in main
    dataset = create_dataset(args, characters)
  File "/home/cjlnet/文档/deep-motion-editing-master/retargeting/datasets/__init__.py", line 28, in create_dataset
    return MixedData(args, character_names)
  File "/home/cjlnet/文档/deep-motion-editing-master/retargeting/datasets/combined_motion.py", line 63, in __init__
    tmp.append(MotionData(new_args))
  File "/home/cjlnet/文档/deep-motion-editing-master/retargeting/datasets/motion_dataset.py", line 30, in __init__
    motions = np.load(file_path, allow_pickle=True)
  File "/home/cjlnet/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './datasets/Mixamo/Aj.npy'

please tell me the reason. Thank you a lot

**Comment by PeizhuoLi** [comment]
Hi, it seems you need to prepare training dataset. Please follow [this](https://github.com/DeepMotionEditing/deep-motion-editing#dataset) section in readme.

**Comment by Lily-Shawn** [comment]
你好，我从把从百度网盘上面下载的数据集放到datasets里面了，我的环境是VMWARE下的Ubuntu系统，抱歉再次叨饶你了
