### ISSUE TITLE
training problem

### ISSUE THREAD

**Issue by Lily-Shawn** [DeepMotionEditing/deep-motion-editing#175]
I run it in VMware Ubuntu. I download Mixamo in Baidupan and put it in datasets. Do I need to do something else? Sorry to interupt again. And I very like your paper.Thanks.
oad from file ./datasets/Mixamo/Aj.npy
Traceback (most recent call last):
File "train.py", line 54, in
main()
File "train.py", line 23, in main
dataset = create_dataset(args, characters)
File "/home/cjlnet/文档/deep-motion-editing-master/retargeting/datasets/init.py", line 28, in create_dataset
return MixedData(args, character_names)
File "/home/cjlnet/文档/deep-motion-editing-master/retargeting/datasets/combined_motion.py", line 63, in init
tmp.append(MotionData(new_args))
File "/home/cjlnet/文档/deep-motion-editing-master/retargeting/datasets/motion_dataset.py", line 30, in init
motions = np.load(file_path, allow_pickle=True)
File "/home/cjlnet/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './datasets/Mixamo/Aj.npy'

**Comment by PeizhuoLi** [comment]
Hi, thanks for your good words. However, the traceback has already gave a very clear start that you should deal with `FileNotFoundError: [Errno 2] No such file or directory: './datasets/Mixamo/Aj.npy'` that could be related to your system environment. I believe it's more efficient that you can solve it on your own (e.g. by search engines) rather post it and wait for the solution.
