### ISSUE TITLE
something is wrong with the file

### ISSUE THREAD

**Issue by jackylee1** [DeepMotionEditing/deep-motion-editing#20]
D:\deep-motion-editing-master\retargeting>python demo.py
命令语法不正确。
loading from ./pretrained/models\topology0
loading from epoch 20000......
load succeed!
loading from ./pretrained/models\topology1
loading from epoch 20000......
load succeed!
C:\Users\anbanglee\miniconda3\envs\avatarify\lib\site-packages\torch\nn\modules\upsampling.py:129: UserWarning: nn.Upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.{} is deprecated. Use nn.functional.interpolate instead.".format(self.name))
命令语法不正确。
Traceback (most recent call last):
  File "eval_single_pair.py", line 99, in <module>
    main()
  File "eval_single_pair.py", line 93, in main
    model.test()
  File "D:\deep-motion-editing-master\retargeting\models\base_model.py", line 96, in test
    self.compute_test_result()
  File "D:\deep-motion-editing-master\retargeting\models\architecture.py", line 296, in compute_test_result
    self.writer[src][i].write_raw(gt[i, ...], 'quaternion', os.path.join(new_path, '{}_gt.bvh'.format(self.id_test)))
  File "D:\deep-motion-editing-master\retargeting\datasets\bvh_writer.py", line 91, in write_raw
    return self.write(rotations, positions, order, path, frametime, root_y=root_y)
  File "D:\deep-motion-editing-master\retargeting\datasets\bvh_writer.py", line 80, in write
    return write_bvh(self.parent, offset, rotations_full, positions, self.names, frametime, order, path)
  File "D:\deep-motion-editing-master\retargeting\datasets\bvh_writer.py", line 10, in write_bvh
    file = open(path, 'w')
FileNotFoundError: [Errno 2] No such file or directory: './pretrained/results/bvh\\Aj\\0_gt.bvh'
Traceback (most recent call last):
  File "demo.py", line 46, in <module>
    example('Aj', 'BigVegas', 'Dancing Running Man.bvh', 'intra', './examples/intra_structure')
  File "demo.py", line 42, in example
    height)
  File "D:\deep-motion-editing-master\retargeting\models\IK.py", line 57, in fix_foot_contact
    anim, name, ftime = BVH.load(input_file)
  File "../utils\BVH.py", line 58, in load
    f = open(filename, "r")
FileNotFoundError: [Errno 2] No such file or directory: './examples/intra_structure\\result.bvh'

(avatarify) D:\deep-motion-editing-master\retargeting>sh demo.sh
'sh' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

(avatarify) D:\deep-motion-editing-master\retargeting>python test.py
Batch [1/4]
命令语法不正确。
loading from ./pretrained/models\topology0
loading from epoch 20000......
load succeed!
loading from ./pretrained/models\topology1
loading from epoch 20000......
load succeed!
  0%|                                                                                          | 0/106 [00:00<?, ?it/s]C:\Users\anbanglee\miniconda3\envs\avatarify\lib\site-packages\torch\nn\modules\upsampling.py:129: UserWarning: nn.Upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.{} is deprecated. Use nn.functional.interpolate instead.".format(self.name))
命令语法不正确。

Traceback (most recent call last):
  File "eval.py", line 37, in <module>
    main()
  File "eval.py", line 33, in main
    model.test()
  File "D:\deep-motion-editing-master\retargeting\models\base_model.py", line 96, in test
    self.compute_test_result()
  File "D:\deep-motion-editing-master\retargeting\models\architecture.py", line 296, in compute_test_result
    self.writer[src][i].write_raw(gt[i, ...], 'quaternion', os.path.join(new_path, '{}_gt.bvh'.format(self.id_test)))
  File "D:\deep-motion-editing-master\retargeting\datasets\bvh_writer.py", line 91, in write_raw
    return self.write(rotations, positions, order, path, frametime, root_y=root_y)
  File "D:\deep-motion-editing-master\retargeting\datasets\bvh_writer.py", line 80, in write
    return write_bvh(self.parent, offset, rotations_full, positions, self.names, frametime, order, path)
  File "D:\deep-motion-editing-master\retargeting\datasets\bvh_writer.py", line 10, in write_bvh
    file = open(path, 'w')
FileNotFoundError: [Errno 2] No such file or directory: './pretrained/results/bvh\\BigVegas\\0_gt.bvh'
Collecting test error...
Traceback (most recent call last):
  File "test.py", line 35, in <module>
    cross_error += full_batch(0)
  File "D:\deep-motion-editing-master\retargeting\get_error.py", line 15, in full_batch
    res.append(batch(char, suffix))
  File "D:\deep-motion-editing-master\retargeting\get_error.py", line 31, in batch
    files = [f for f in os.listdir(new_p) if
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: './pretrained/results/bvh\\Mousey_m'

**Comment by PeizhuoLi** [comment]
Running on Windows is not supported. Please try Linux or macOS. More details about environment and platform will be added to README.

**Comment by gemlongman** [comment]
[root@centos /data/gem/code/deep-motion-editing/retargeting]# sh demo.sh
output_filename=./examples/intra_structure/result.bvh --test_type=intra
loading from ./pretrained/models/topology0
loading from epoch 20000......
load succeed!
loading from ./pretrained/models/topology1
loading from epoch 20000......
load succeed!
Traceback (most recent call last):
  File "demo.py", line 47, in <module>
    example('Aj', 'BigVegas', 'Dancing Running Man.bvh', 'intra', './examples/intra_structure')
  File "demo.py", line 43, in example
    height)
  File "/data/gemhygao/code/deep-motion-editing/retargeting/models/IK.py", line 57, in fix_foot_contact
    anim, name, ftime = BVH.load(input_file)
  File "../utils/BVH.py", line 58, in load
    f = open(filename, "r")
FileNotFoundError: [Errno 2] No such file or directory: './examples/intra_structure/result.bvh'

I'm sorry if I bothered you, why need it read a result?

**Comment by gemlongman** [comment]
my problem is pytorch,I just update it
conda install pytorch torchvision cpuonly -c pytorch
