### ISSUE TITLE
使用新骨架进行重定向后，出现模型维度不匹配的问题

### ISSUE THREAD

**Issue by huang-1030** [DeepMotionEditing/deep-motion-editing#222]
感谢分享您的工作！
在使用重定向的工程中，我使用了lafan1的骨架作为输入，但当运行demo.py后，出现如下模型加载的问题，请问这种情况我是需要使用该骨架重新训练吗？

Traceback (most recent call last):
  File "eval_single_pair.py", line 97, in <module>
    main()
  File "eval_single_pair.py", line 76, in main
    model.load(epoch=20000)
  File "E:\python\motion_editing\retargeting\models\architecture.py", line 274, in load
    model.load(os.path.join(self.model_save_dir, 'topology{}'.format(i)), epoch)
  File "E:\python\motion_editing\retargeting\models\integrated.py", line 82, in load
    self.auto_encoder.load_state_dict(torch.load(os.path.join(path, 'auto_encoder.pt'), map_location=self.args.cuda_device), False)
  File "E:\anaconda\lib\site-packages\torch\nn\modules\module.py", line 1483, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for AE:
	size mismatch for enc.layers.0.0.mask: copying a param with shape torch.Size([184, 92, 15]) from checkpoint, the shape in current model is torch.Size([176, 88, 15]).
	size mismatch for enc.layers.0.0.weight: copying a param with shape torch.Size([184, 92, 15]) from checkpoint, the shape in current model is torch.Size([176, 88, 15]).
	size mismatch for enc.layers.0.0.bias: copying a param with shape torch.Size([184]) from checkpoint, the shape in current model is torch.Size([176]).
	size mismatch for enc.layers.0.0.offset_enc.bias: copying a param with shape torch.Size([184]) from checkpoint, the shape in current model is torch.Size([176]).
	size mismatch for enc.layers.0.0.offset_enc.weight: copying a param with shape torch.Size([184, 69]) from checkpoint, the shape in current model is torch.Size([176, 66]).
	size mismatch for enc.layers.0.0.offset_enc.mask: copying a param with shape torch.Size([184, 69]) from checkpoint, the shape in current model is torch.Size([176, 66]).
	size mismatch for enc.layers.0.1.weight: copying a param with shape torch.Size([96, 184]) from checkpoint, the shape in current model is torch.Size([96, 176]).
	size mismatch for dec.layers.1.1.weight: copying a param with shape torch.Size([184, 96]) from checkpoint, the shape in current model is torch.Size([176, 96]).
	size mismatch for dec.layers.1.2.mask: copying a param with shape torch.Size([92, 184, 15]) from checkpoint, the shape in current model is torch.Size([88, 176, 15]).
	size mismatch for dec.layers.1.2.weight: copying a param with shape torch.Size([92, 184, 15]) from checkpoint, the shape in current model is torch.Size([88, 176, 15]).
	size mismatch for dec.layers.1.2.bias: copying a param with shape torch.Size([92]) from checkpoint, the shape in current model is torch.Size([88]).
	size mismatch for dec.layers.1.2.offset_enc.bias: copying a param with shape torch.Size([92]) from checkpoint, the shape in current model is torch.Size([88]).
	size mismatch for dec.layers.1.2.offset_enc.weight: copying a param with shape torch.Size([92, 69]) from checkpoint, the shape in current model is torch.Size([88, 66]).
	size mismatch for dec.layers.1.2.offset_enc.mask: copying a param with shape torch.Size([92, 69]) from checkpoint, the shape in current model is torch.Size([88, 66]).
	size mismatch for dec.unpools.1.weight: copying a param with shape torch.Size([184, 96]) from checkpoint, the shape in current model is torch.Size([176, 96]).
	size mismatch for dec.enc.layers.0.0.mask: copying a param with shape torch.Size([184, 92, 15]) from checkpoint, the shape in current model is torch.Size([176, 88, 15]).
	size mismatch for dec.enc.layers.0.0.weight: copying a param with shape torch.Size([184, 92, 15]) from checkpoint, the shape in current model is torch.Size([176, 88, 15]).
	size mismatch for dec.enc.layers.0.0.bias: copying a param with shape torch.Size([184]) from checkpoint, the shape in current model is torch.Size([176]).
	size mismatch for dec.enc.layers.0.0.offset_enc.bias: copying a param with shape torch.Size([184]) from checkpoint, the shape in current model is torch.Size([176]).
	size mismatch for dec.enc.layers.0.0.offset_enc.weight: copying a param with shape torch.Size([184, 69]) from checkpoint, the shape in current model is torch.Size([176, 66]).
	size mismatch for dec.enc.layers.0.0.offset_enc.mask: copying a param with shape torch.Size([184, 69]) from checkpoint, the shape in current model is torch.Size([176, 66]).
	size mismatch for dec.enc.layers.0.1.weight: copying a param with shape torch.Size([96, 184]) from checkpoint, the shape in current model is torch.Size([96, 176]).

**Comment by zzk88862** [comment]
> 感谢分享您的工作！ 在使用重定向的工程中，我使用了lafan1的骨架作为输入，但当运行demo.py后，出现如下模型加载的问题，请问这种情况我是需要使用该骨架重新训练吗？
> 
> Traceback (most recent call last): File "eval_single_pair.py", line 97, in main() File "eval_single_pair.py", line 76, in main model.load(epoch=20000) File "E:\python\motion_editing\retargeting\models\architecture.py", line 274, in load model.load(os.path.join(self.model_save_dir, 'topology{}'.format(i)), epoch) File "E:\python\motion_editing\retargeting\models\integrated.py", line 82, in load self.auto_encoder.load_state_dict(torch.load(os.path.join(path, 'auto_encoder.pt'), map_location=self.args.cuda_device), False) File "E:\anaconda\lib\site-packages\torch\nn\modules\module.py", line 1483, in load_state_dict self.**class**.**name**, "\n\t".join(error_msgs))) RuntimeError: Error(s) in loading state_dict for AE: size mismatch for enc.layers.0.0.mask: copying a param with shape torch.Size([184, 92, 15]) from checkpoint, the shape in current model is torch.Size([176, 88, 15]). size mismatch for enc.layers.0.0.weight: copying a param with shape torch.Size([184, 92, 15]) from checkpoint, the shape in current model is torch.Size([176, 88, 15]). size mismatch for enc.layers.0.0.bias: copying a param with shape torch.Size([184]) from checkpoint, the shape in current model is torch.Size([176]). size mismatch for enc.layers.0.0.offset_enc.bias: copying a param with shape torch.Size([184]) from checkpoint, the shape in current model is torch.Size([176]). size mismatch for enc.layers.0.0.offset_enc.weight: copying a param with shape torch.Size([184, 69]) from checkpoint, the shape in current model is torch.Size([176, 66]). size mismatch for enc.layers.0.0.offset_enc.mask: copying a param with shape torch.Size([184, 69]) from checkpoint, the shape in current model is torch.Size([176, 66]). size mismatch for enc.layers.0.1.weight: copying a param with shape torch.Size([96, 184]) from checkpoint, the shape in current model is torch.Size([96, 176]). size mismatch for dec.layers.1.1.weight: copying a param with shape torch.Size([184, 96]) from checkpoint, the shape in current model is torch.Size([176, 96]). size mismatch for dec.layers.1.2.mask: copying a param with shape torch.Size([92, 184, 15]) from checkpoint, the shape in current model is torch.Size([88, 176, 15]). size mismatch for dec.layers.1.2.weight: copying a param with shape torch.Size([92, 184, 15]) from checkpoint, the shape in current model is torch.Size([88, 176, 15]). size mismatch for dec.layers.1.2.bias: copying a param with shape torch.Size([92]) from checkpoint, the shape in current model is torch.Size([88]). size mismatch for dec.layers.1.2.offset_enc.bias: copying a param with shape torch.Size([92]) from checkpoint, the shape in current model is torch.Size([88]). size mismatch for dec.layers.1.2.offset_enc.weight: copying a param with shape torch.Size([92, 69]) from checkpoint, the shape in current model is torch.Size([88, 66]). size mismatch for dec.layers.1.2.offset_enc.mask: copying a param with shape torch.Size([92, 69]) from checkpoint, the shape in current model is torch.Size([88, 66]). size mismatch for dec.unpools.1.weight: copying a param with shape torch.Size([184, 96]) from checkpoint, the shape in current model is torch.Size([176, 96]). size mismatch for dec.enc.layers.0.0.mask: copying a param with shape torch.Size([184, 92, 15]) from checkpoint, the shape in current model is torch.Size([176, 88, 15]). size mismatch for dec.enc.layers.0.0.weight: copying a param with shape torch.Size([184, 92, 15]) from checkpoint, the shape in current model is torch.Size([176, 88, 15]). size mismatch for dec.enc.layers.0.0.bias: copying a param with shape torch.Size([184]) from checkpoint, the shape in current model is torch.Size([176]). size mismatch for dec.enc.layers.0.0.offset_enc.bias: copying a param with shape torch.Size([184]) from checkpoint, the shape in current model is torch.Size([176]). size mismatch for dec.enc.layers.0.0.offset_enc.weight: copying a param with shape torch.Size([184, 69]) from checkpoint, the shape in current model is torch.Size([176, 66]). size mismatch for dec.enc.layers.0.0.offset_enc.mask: copying a param with shape torch.Size([184, 69]) from checkpoint, the shape in current model is torch.Size([176, 66]). size mismatch for dec.enc.layers.0.1.weight: copying a param with shape torch.Size([96, 184]) from checkpoint, the shape in current model is torch.Size([96, 176]).

我也遇到相同的问题，请问你解决了吗

**Comment by CHDTevior** [comment]
same problem
