### ISSUE TITLE
Use my own data for training, but there is no loss value

### ISSUE THREAD

**Issue by wuxiaolianggit** [DeepMotionEditing/deep-motion-editing#56]
Excuse me, I use my own data for training, but there is no loss value. Is it because there is a problem with my default configuration？

====characters=  [['mouse'], ['strong']]
load from file ./datasets/Mixamo/mouse.npy
Window count: 4, total frame (without downsampling): 3572
load from file ./datasets/Mixamo/strong.npy
Window count: 4, total frame (without downsampling): 3560

No scalar data was found.
Probable causes:

    You haven’t written any scalar data to your event files.
    TensorBoard can’t find your event files.

If you’re new to using TensorBoard, and want to find out how to add data and set up your event files, check out the README and perhaps the TensorBoard tutorial.

If you think TensorBoard is configured properly, please see the section of the README devoted to missing data problems and consider filing an issue on GitHub. 

@kfiraberman

**Comment by PeizhuoLi** [comment]
You can use --verbose=1 to see if training is really working. Regarding the tensorboard problem, I'm not quite sure what happened. Maybe check if the logs directory is empty and make sure you are using the correct path for tensorboard.

**Comment by wuxiaolianggit** [comment]
Thank you very much for your reply. I have solved this problem. 
But I use the new training model to test, there are some errors, how to solve it?


loading from ./pretrained/models/topology0
loading from epoch 2000......
load succeed!
loading from ./pretrained/models/topology1
loading from epoch 2000......
load succeed!
Traceback (most recent call last):
  File "evel_single_pair_1.py", line 98, in <module>
    main()
  File "evel_single_pair_1.py", line 92, in main
    model.test()
  File "/home/wuxiaoliang/docker/motion_retarget/deep-motion-editing/retargeting/models/base_model.py", line 95, in test
    self.forward()
  File "/home/wuxiaoliang/docker/motion_retarget/deep-motion-editing/retargeting/models/architecture.py", line 103, in forward
    latent, res = self.models[i].auto_encoder(motion, offsets)
  File "/home/wuxiaoliang/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wuxiaoliang/docker/motion_retarget/deep-motion-editing/retargeting/models/enc_and_dec.py", line 133, in forward
    latent = self.enc(input, offset)
  File "/home/wuxiaoliang/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wuxiaoliang/docker/motion_retarget/deep-motion-editing/retargeting/models/enc_and_dec.py", line 66, in forward
    input = layer(input)
  File "/home/wuxiaoliang/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wuxiaoliang/anaconda3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/wuxiaoliang/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wuxiaoliang/docker/motion_retarget/deep-motion-editing/retargeting/models/skeleton.py", line 95, in forward
    res = F.conv1d(F.pad(input, self._padding_repeated_twice, mode=self.padding_mode),
  File "/home/wuxiaoliang/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py", line 3397, in _pad
    return torch._C._nn.reflection_pad1d(input, pad)
RuntimeError: Argument #4: Padding size should be less than the corresponding input dimension, but got: padding (7, 7) at dimension 2 of input [1, 112, 7]
@PeizhuoLi

**Comment by PeizhuoLi** [comment]
Hi, sorry for the inconvenience. The default hyper-parameter of number of layers was mistakenly set to 3. It should be 2. You can add --num_layer=2 in training parameter or pull the newest code and retrain your model.

**Comment by wuxiaolianggit** [comment]
Thank you very much for your answer to my question。
