### ISSUE TITLE
all windows length is -1

### ISSUE THREAD

**Issue by wuxiaolianggit** [DeepMotionEditing/deep-motion-editing#63]
================================windows length is  -1
Traceback (most recent call last):
  File "./datasets/preprocess.py", line 72, in <module>
    write_statistics(character, './datasets/Mixamo/mean_var/')
  File "./datasets/preprocess.py", line 34, in write_statistics
    dataset = MotionData(new_args)
  File "/home/wuxiaoliang/docker/motion_retarget/deep-motion-editing/retargeting/datasets/motion_dataset.py", line 33, in __init__
    new_windows = self.get_windows(motions)
  File "/home/wuxiaoliang/docker/motion_retarget/deep-motion-editing/retargeting/datasets/motion_dataset.py", line 106, in get_windows
    return torch.cat(new_windows)
RuntimeError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors.  Available functions are [CPUTensorId, CUDATensorId, QuantizedCPUTensorId, VariableTensorId]

how to solve the problem? @kfiraberman

**Comment by PeizhuoLi** [comment]
BVH files in wild can be very different, thus we can only promise our code working on provided dataset without any change. Some minor changes could be inevitable in order to work on your own dataset. Besides, we welcome all pull requests that enhance compatibility and robustness.

**Comment by wuxiaolianggit** [comment]
Thank you very much for your reply
